crm/urls.py
from django.urls import path
from . import views

app_name='crm'

urlpatterns=[
    path('client/create/', views.ClientCreate.as_view(), name='client_create'),
	path('client/list/',views.client_list,name='clients'),
	path('contact/list/',views.contact_list,name='contacts'),
    path('contact/create/', views.ContactCreate.as_view(), name='contact_create'),
	path('communications/index/',views.communications,name='communications'),
	path('communications/filters/',views.filter_parameter,name='filter_params'),
	path('communications/sms/',views.broadcast_sms,name='send_bulk_sms'),
	path('communications/sms/single/',views.broadcast_single_sms,name='send_single_sms'),
	path('communications/emails/',views.broadcast_emails,name='send_mass_email'),
	path('communications/emails/single/',views.broadcast_single_email,name='send_single_email'),
	path('communications/existing_filter/<int:search_id>/',views.use_existing_filter,name='use_existing_filter'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> performancesuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('select2/', include('django_select2.urls')),
    path('bs_index/',views.bootstrap_index),
    path('crm/',include('crm.urls',namespace='crm')),

    # path('accounts/', include('allauth.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'performance ADMINISTRATION'

admin.autodiscover()
admin.site.enable_nav_sidebar = False

taskmanager/urls.py
"""Task Manager URL Configuration

"""
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from taskmanager import views

# from . import views

app_name = 'taskmanager'
router = DefaultRouter()
router.register("task",views.TaskCreate)


urlpatterns = [
    path('', views.index, name='index'),
    path('dates/',views.postDateRange,name='date_ranges'),
    path('ajax/charts/deadline/', views.deadline_score, name='chart_deadline'),
    path('ajax/charts/resubmission/', views.resubmission_score, name='chart_resubmission'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('ajax/charts/reset/', views.reset_score, name='chart_reset'),
    path('ajax/charts/quality/', views.quality_score, name='chart_quality'),
    path('charts/planning/', views.planning_score, name='chart_planning'),
    path('teams/<int:team_id>/', views.team_detail, name='team_detail'),
    path('team_details/<int:team_id>/', views.team_details, name='team_details'),
    path('teams/create/', views.team_create, name='team_create'),
    path('teams/<int:team_id>/remove-member/', views.team_remove_member, name='team_remove_member'),
    path('teams/<int:team_id>/add-member/', views.team_add_member, name='team_add_member'),
    path('teams/<int:team_id>/delete/', views.team_delete, name='team_delete'),
    path('my-tasks/', views.tasks, name='task_my_tasks'),
    path('team-tasks/<int:team_id>/', views.team_tasks, name='team_tasks'),
    path('tasks/<int:pk>/update/', views.TaskUpdate.as_view(), name='task_update'),
    path('tasks/<int:pk>/reassign/', views.Reassigning.as_view(), name='task_reassign'),
    path('tasks/invoice_assignment/', views.RequestInvoice.as_view(), name='invoice_assignment'),
    path('tasks/<int:pk>/extend/', views.ExtendDeadline.as_view(), name='task_extend'),
    path('tasks/bid_create/', views.TaskBidCreate.as_view(), name='task_bid_create'),
    path('tasks/report_create/', views.ReportCreate.as_view(), name='report_create'),
    path('tasks/<int:pk>/bid/', views.TaskBid.as_view(), name='task_bid'),
    path('tasks/<int:pk>/rating/', views.Rating.as_view(), name='task_rating'),
    path('sub_tasks/<int:pk>/rating/', views.SubTaskRating.as_view(), name='subtask_rating'),
    path('sub_tasks/<int:pk>/return/', views.Revision.as_view(), name='subtask_return'),
    path('tasks/<int:task_id>/comment/', views.task_comment, name='task_comment'),
    path('tasks/<int:task_id>/accept/', views.task_accept, name='task_accept'),
    path('tasks/<int:task_id>/resubmit/', views.task_resubmit, name='task_resubmit'),
    path('tasks/<int:task_id>/mark-completed/', views.task_mark_completed, name='task_mark_completed'),
    path('tasks/<int:task_id>/mark-pending-approved/', views.task_mark_pending_approved, name='task_mark_pending_approved'),
    path('tasks/<int:task_id>/return-revision/', views.task_mark_revision, name='task_mark_revision'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('tasks/create/', views.TaskCreate.as_view(), name='task_create'),
    path('tasks/search/', views.task_search, name='task_search'),
    path('tasks/sources/',views.task_sources,name='task_source'),
    path('signup/', views.signup, name='signup'),
    path('ajax/load-members/', views.load_members, name='ajax_load_members'),
    path('ajax/load-projects/', views.load_projects, name='ajax_load_projects'),

]


taskmanager/models.py
from django.db import models

taskmanager/models/tasks.py
import datetime
from datetime import datetime
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from crm.models import ClientManager
from django.contrib.auth.models import User
from django.db.models.signals import post_save,pre_save,post_init,pre_init
from django.dispatch import receiver
from django.utils import timezone
from django.db.models.signals import post_save,post_init
from django.dispatch import receiver
from django.db.models import Q
from dateutil.relativedelta import relativedelta
from setup.utils import convert_to_seconds
from djmoney.models.fields import MoneyField

# Get user model defined in settings.AUTH_USER_MODEL
# Better to call get_user_model in pluggable app instead of imporing User from django.contrib.auth.models
UserModel = get_user_model()




class Team(models.Model):
    """
    Not using Django's built-in Group model because we want
    to save the creater of team.
    """
    name = models.CharField(max_length=50)
    desc = models.TextField(default='', max_length=1024, blank=True)
    leader = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='leading_teams')
    members = models.ManyToManyField(UserModel)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taskmanager:team_detail", kwargs={"team_id": self.id})

    def get_absolute_urls(self):
        return reverse("taskmanager:team_details", kwargs={"team_id": self.id})


    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Teams"


class Task(models.Model):
    ASSIGNMENT_TYPE=[
        ('one','Type One'),
        ('two','Type Two'),
        ('other','OTHER')
    ]
    RATING_RANGE=[
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5')
    ]
    STATUS_CHOICES = (
        ('BID',  'Successfully Bidded'),
        ('NBID', 'Unsuccessful Bid'),
        ('PLAN', 'Begin'),
        ('PROG', 'On going'),
        ('COMP', 'Completed'),
        ('RES',  'Resubmit'),
        ('PA',   'Pending Approval'),
        ('APP',  'Approved'),
        ('REV',  'Revise'),
        ('RET',  'Resubmitted'),
        ('INV',   'Invoiced')
    )
    DEFAULT_ASSIGMENT_TYPE=1
    title = models.CharField('Project Name',max_length=1220,null=True)
    assignment_type=models.CharField('*',max_length=1220,null=True,blank=True,)
    assignment_typeset=models.ForeignKey('self',on_delete=models.CASCADE,null=True,verbose_name='Project Type',blank=True)
    desc = models.TextField(default="test", max_length=1024, null=True,blank=True)
    client_code = models.TextField(default="test", max_length=1024, null=True,blank=True)
    client_name = models.CharField('Client',max_length=50,null=True)
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default='PLAN',null=True)

    creator = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='created_tasks',null=True)

    # A task can be assigned to one or many users
    assigned_to = models.ManyToManyField(UserModel, help_text="Press ctrl to select multiple",verbose_name='Project Coordinator')
    reassign_reason=models.CharField(max_length=1024,null=True,blank=True)
    return_reason=models.CharField(max_length=1024,null=True,blank=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True)
    planned_date = models.DateField(auto_now_add=True)
    accepted_date = models.DateField(null=True, blank=True)
    accepted_by = models.ForeignKey(UserModel, on_delete=models.SET_NULL, null=True, related_name='accepted_tasks',
                                    blank=True)
    due_date = models.DateTimeField('Project Due Date',null=True)
    notification_date=models.DateField(null=True,blank=True)
    unsuccess_reason=models.CharField(max_length=1028,null=True,blank=True)
    revised_due_date = models.DateTimeField(null=True, blank=True)
    date_accepted = models.DateTimeField(null=True, blank=True)
    completed_date = models.DateTimeField(null=True, blank=True)
    rating=models.IntegerField(choices=RATING_RANGE,null=True,blank=True)
    content=models.CharField('comments',max_length=500,null=True,blank=True)
    team_leader=models.BooleanField(default=False)
    approved_date=models.DateTimeField(null=True,blank=True)
    

    def __str__(self):
        return self.title if self.title else ''

    def get_absolute_url(self):
        return reverse("taskmanager:task_detail", kwargs={"task_id": self.id})
    

    @property
    def deadline_score(self):
        approved_delta=relativedelta(self.date_accepted,self.approved_date)
        deadline_delta=relativedelta(self.date_accepted,self.due_date)
        if deadline_delta and approved_delta:
            deadline_score=convert_to_seconds(approved_delta)/convert_to_seconds(deadline_delta)
            return round(deadline_score,3)

    @property
    def task_resubmission_score(self):
        resubmitted_tasks=TaskAnalysis.objects.filter(Q(resubmits='RES') & Q(task__creator=self.creator)).count()
        total_tasks=Task.objects.filter(creator=self.creator).count()
        resubmission_score=(1-(resubmitted_tasks/total_tasks))
        return round(resubmission_score,3)


    @property
    def task_deadline_reset_score(self):
        reset_tasks=TaskAnalysis.objects.filter(~Q(resubmits='RES') & Q(task__creator=self.creator)).count()
        total_tasks=Task.objects.filter(creator=self.creator).count()
        deadline_reset_score=(1-(reset_tasks/total_tasks))
        return round(deadline_reset_score,3)


    @property
    def task_count(self):
        completed_tasks=self.subtask.filter(Q(status='COMP') | Q(status='APP')).count()
        total_tasks=self.subtask.all().count()
        if completed_tasks == 0 or total_tasks == 0:
            rate=0
        else:
            rate = completed_tasks/total_tasks
        return round(rate * 100)


    # Has due date for an instance of this object passed?
    def is_overdated(self):
        """Returns whether the Tasks's due date has passed or not."""
        if self.due_date and timezone.now() > self.due_date:
            return True
        else:
            return False
            


        
    
    class Meta:
        ordering = ["planned_date"]
        verbose_name_plural = "Tasks"





class SubTask(models.Model):
    STATUS_CHOICES = (
        ('PLAN', 'To Accept'),
        ('PROG', 'On going'),
        ('COMP', 'Completed'),
        ('RES',  'Resubmit'),
        ('PA',   'Pending Approval'),
        ('APP',  'Approved'),
        ('REV',  'Revise'),
        ('RET',  'Resubmitted'),
        ('INV',  'Invoiced')
    )
    RATING_RANGE=[
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5')
    ]
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default='PLAN',null=True)
    extension_reason=models.CharField(max_length=1024,null=True,blank=True)
    return_reason=models.CharField(max_length=1024,null=True,blank=True)
    reassign_reason=models.CharField(max_length=1024,null=True,blank=True)
    name=models.CharField(max_length=300)
    task=models.ForeignKey(Task,related_name='subtask',on_delete=models.CASCADE)
    member_assigned=models.ForeignKey(UserModel,related_name='assignee_subtask', on_delete=models.CASCADE,verbose_name='Assign to:')
    team=models.ForeignKey(Team,on_delete=models.CASCADE,null=True,blank=True)
    task_due_date=models.DateField('Task Due Date:',null=True)
    accepted_by = models.ForeignKey(UserModel, on_delete=models.SET_NULL, null=True, related_name='accepted_subtasks',
                                    blank=True)
    prior_task=models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)
    date_accepted = models.DateField(null=True, blank=True)
    deadline_final=models.DateField(null=True,blank=True)
    approved_date=models.DateField(null=True,blank=True)
    completed_date = models.DateField(null=True, blank=True)
    revised_due_date=models.DateField(null=True,blank=True)
    rating=models.IntegerField(choices=RATING_RANGE,null=True, blank=True)
    content=models.CharField('comments',max_length=500,null=True,blank=True)
    

    def __str__(self):
        return self.name



    @property
    def subtask_deadline_score(self):
        deadline_delta=relativedelta(self.date_accepted,self.task_due_date)
        approved_delta=relativedelta(self.date_accepted,self.approved_date)
        if deadline_delta and approved_delta:
            deadline_score=convert_to_seconds(deadline_delta)/convert_to_seconds(approved_delta)
            return round((1/deadline_score),3)

    @property
    def subtask_planning_score(self):
        approved_delta=relativedelta(self.task_due_date,self.approved_date)
        deadline_delta=relativedelta(self.task_due_date,self.date_accepted)
        if deadline_delta and approved_delta:
            planning_score=convert_to_seconds(approved_delta)/convert_to_seconds(deadline_delta)
            return round((1-planning_score),3)



    @property
    def subtask_rate(self):
        completed_tasks=SubTask.objects.filter(Q(status='COMP') & Q(member_assigned=self.member_assigned)).count()
        total_tasks=SubTask.objects.filter(Q(member_assigned=self.member_assigned)).count()
        # import pdb; pdb.set_trace()
        if completed_tasks == 0 or total_tasks == 0:
            rate=0
        else:
            rate = completed_tasks/total_tasks
        return round(rate * 100)

    @property
    def subtask_resubmission_score(self):
        resubmitted_tasks=SubTaskAnalysis.objects.filter(Q(resubmits='RES') & Q(subtask__member_assigned=self.member_assigned)).count()
        total_tasks=SubTask.objects.filter(member_assigned=self.member_assigned).count()
        resubmission_score=(1-(resubmitted_tasks/total_tasks))
        return round(resubmission_score,3)


    @property
    def subtask_deadline_reset_score(self):

taskmanager/views/search.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.views.decorators.http import require_http_methods

from taskmanager.models import Task

@login_required
@require_http_methods(["GET"])
def task_search(request):
    """
    Search for tasks user has permission to see.
    """
    query_string = ""
    found_tasks = None
    if ("q" in request.GET) and request.GET["q"].strip():
        query_string = request.GET["q"]

        found_tasks = Task.objects.filter(
            (Q(title__icontains=query_string) | Q(desc__icontains=query_string)) &
            (Q(creator=request.user) | Q(assigned_to=request.user))
        ).distinct()
    else:
        messages.error(request, "Missing search parameter!")

    context = {"query_string": query_string, "found_tasks": found_tasks}
    return render(request, "taskmanager/task_search_results.html", context)

templates/taskmanager/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
  <head lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'taskmanager/w3.css' %}">
    <link rel = "stylesheet" href = "https://www.w3schools.com/lib/w3.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- Sidebar -->
  <div class="w3-sidebar w3-bar-block w3-border-right w3-animate-left" style="display:none" id="mySidebar">
    <button onclick="w3_close()" class="w3-bar-item w3-large">Close &times;</button>
    {% if user.is_authenticated %}
    {% load crispy_forms_tags %}
      <strong class="w3-bar-item"><i>{{ user.username }}</i></strong>
      <a href="{% url 'taskmanager:index' %}" class="w3-bar-item w3-button">Departments</a>
      <a href="{% url 'taskmanager:task_my_tasks' %}" class="w3-bar-item w3-button">My Tasks</a>
      <a href="{% url 'taskmanager:task_create' %}" class="w3-bar-item w3-button">Add a Task</a>
      <a href="{% url 'taskmanager:team_create' %}" class="w3-bar-item w3-button">Create a Team</a>
      <form method="get" action="{% url 'taskmanager:task_search' %}" class="w3-margin-top w3-margin-bottom">
        <input type="text" name="q" class="w3-input w3-border" placeholder="Search task" required>
        <input type="submit" value="Search" class="w3-button w3-grey w3-margin">
      </form>
    {% else %}
      <a href="{% url 'taskmanager:signup' %}" class="w3-bar-item w3-button">Sign Up</a>
    {% endif %}
  </div>

  <!-- Page Content -->
  <div class="w3-teal">
    <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">+</button>
    <div class="w3-container">
      <h1 style="text-shadow:1px 1px 0 #444; text-align:center;">Performance and Task Manager System</h1>
    </div>
  </div>

  <div class="w3-container">
    {% if messages %}
      {% for message in messages %}
        <div class="w3-panel w3-round-xlarge {% if message.tags == 'success' %}w3-pale-green{% else %}w3-pale-red{% endif %}" style="padding:10px">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
  </div>

  <script>
  function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
  }
  function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
  }
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </body>
</html>

templates/taskmanager/email.html
<div class="container">
<p>Timesheet for {{taskset.title}}</p>

    <table style="border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);">
    <thead>
        <tr style="background-color: #009879;
        color: #ffffff;
        text-align: left;">
            <th>Subtask Details</th>
            <th>Client</th>
            <th>Project</th>
            <th>Deadline For Project</th>
        </tr>
    </thead>
    <tbody style="border-bottom: 2px solid #009879;">
        <tr style="border-bottom: 1px solid #dddddd;">
            <td style="padding: 12px 15px;">
                <ul>
                    {% for subtask in taskset.subtask.all %}
                    <li>
                        {{subtask}} assigned to {{subtask.member_assigned}} due by {{subtask.task_due_date}}
                    </li>
                    {% endfor %}
                </ul>
            </td>
            <td style="padding: 12px 15px;">{{taskset.client_name}}</td>
            <td style="padding: 12px 15px;">{{taskset.title}}</td>
            <td style="padding: 12px 15px;">{{taskset.due_date}}</td>
        </tr>
    </tbody>
    </table>

    <p>Go to system: {{site}}</p>
</div>

templates/taskmanager/task_create.html
{% extends '_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block navheader %}
{% endblock %}
 
{% block content %}

<div class="container">
    {% if  messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags}} alert-info"{% endif %}>
            {{ message }}
            <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-header bg-success text-white">
            {% if create %}
            KickStart Project
            {% elif update %}
            Edit Project
            {% elif revision %}
            Return Task for revision
            {% elif bidding %}
            Bid Analyzer
            {% elif create_client %}
            Add Client
            {% elif reports %}
            Generate Report
            {% elif create_contact %}
            Add Contact
            {% else %}
            Rate Task
            {% endif %}
        </div>
        <div class="card-body">
            <hr/>
                {% crispy form %}
            
        </div>
    </div>    
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

<script src="{% static 'js/jquery.formset.js' %}"></script>

<script>
    function renewDatePickers() {
        $('.datetimeinput').datetimepicker('destroy');
        $(".datetimeinput").datetimepicker({format:'Y-m-d H:i'});
    }

    $(renewDatePickers);

    // $(function() {
    //     $('.form-row.inline.{{ form.prefix }}').formset({
    //         prefix: '{{ form.prefix }}',
    //         added: renewDatePickers // Event -- read inline docs
    //     });
    // })

    $(function () {
        $(".datetimeinput").datetimepicker({
            format:'Y-m-d H:i',
        });
    });

    $("#id_team").change(function(){
            var url = "{% url 'taskmanager:ajax_load_members' %}"
            var teamId = $(this).val();  

            $.ajax({                          // initialize an ajax request
            url:url,                        // set the url of the request
            data:{
                'team': teamId 
            },
            success: function (data){                          // data is the return of the specific maptype view
                // console.log(data);
                $("#id_assigned_to").html(data);
            }
            });
    });

    $("#id_team").change(function(){
            var url = "{% url 'taskmanager:ajax_load_projects' %}"
            var teamId = $(this).val();  

            $.ajax({                          // initialize an ajax request
            url:url,                        // set the url of the request
            data:{
                'teamset': teamId 
            },
            success: function (data){                          // data is the return of the specific maptype view
                // console.log(data);
                $("#id_assignment_typeset").html(data);                   // replace contents of maptype with data that came from the server
            }
            });
    });
    

    jQuery('#id_assignment_typeset').on('change', (e) => {
    // You can also do this with document.querySelector('')
    var assignment_typeset=$("#id_assignment_typeset option:selected").text();
    
    if (assignment_typeset=='other') {
        // console.log(assignment_typeset+1);
        // document.getElementById("id_assignment_typeset").style.color = "green";
        jQuery('#id_assignment_type').show();                        
    } else {               
        jQuery('#id_assignment_type').hide();
    }
    }); 
    
    let form_count=Number($("#id_sub_task_count").val());
    console.log(form_count);

    $("#add-another").click(function(){
        form_count ++;

        let element=$('<input type="text"/>');
        element.attr('name','sub_task_'+form_count);
        let elements=$('<input type="text"/>');
        element.attr('name','member_assigned_sub_task_'+form_count);
        $("#forms").append(element);
        $("#forms").append(elements);

        $("[name=sub_task_count]").val(form_count);
    })
</script>

{% endblock %}

templates/taskmanager/task_search_results.html
{% extends '_layout.html' %}

{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block content %}
  <h2>{{ found_tasks.count }} search results for : "{{ query_string }}"</h2>
  {% if found_tasks %}
    <table class="w3-table w3-striped w3-bordered w3-card-4 w3-hoverable">
      <tr class="w3-green">
        <th>Title</th>
        <th>Team</th>
        <th>Created By</th>
        <th>Assigned to</th>
        <th>Due Date</th>
        <th>Status</th>
        <th>Completed Date</th>
      </tr>
      {% for task in found_tasks %}
        <tr>
          <td><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></td>
          <td>
            {% if task.team %}
              <a href={{ task.team.get_absolute_url }}>{{ task.team }}</a>
            {% else %}
              ----
            {% endif %}
          </td>
          <td>{{ task.creator }}</td>
          <td>
            <ul class="w3-ul" style="width:36%">
              {% for u in task.assigned_to.all %}
                <li><i>{{ u }}</i></li>
              {% endfor %}
            </ul>
          </td>
          <td>{{ task.due_date }}</td>
          <td>{{ task.get_status_display }}</td>
          <td>{{ task.completed_date }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}

{% endblock %}

templates/taskmanager/team_dropdown.html
{% if load_members %}
<option value="">---------</option>
{% for member in members %}
<option value="{{ member.pk }}">{{ member }}</option>
{% endfor %}
{% endif %}


{% if load_projects %}
<option value="">---------</option>
{% for assignment_type in assignment_typeset %}
<option value="{{ assignment_type.pk }}">{{ assignment_type }}</option>
{% endfor %}
{% endif %}