crm/urls.py
from django.urls import path
from . import views

app_name='crm'

urlpatterns=[
    path('client/create/', views.ClientCreate.as_view(), name='client_create'),
	path('client/list/',views.client_list,name='clients'),
	path('contact/list/',views.contact_list,name='contacts'),
    path('contact/create/', views.ContactCreate.as_view(), name='contact_create'),
	path('communications/index/',views.communications,name='communications'),
	path('communications/filters/',views.filter_parameter,name='filter_params'),
	path('communications/sms/',views.broadcast_sms,name='send_bulk_sms'),
	path('communications/sms/single/',views.broadcast_single_sms,name='send_single_sms'),
	path('communications/emails/',views.broadcast_emails,name='send_mass_email'),
	path('communications/emails/single/',views.broadcast_single_email,name='send_single_email'),
	path('communications/existing_filter/<int:search_id>/',views.use_existing_filter,name='use_existing_filter'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> performancesuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('select2/', include('django_select2.urls')),
    path('bs_index/',views.bootstrap_index),
    path('crm/',include('crm.urls',namespace='crm')),

    # path('accounts/', include('allauth.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'performance ADMINISTRATION'

admin.autodiscover()
admin.site.enable_nav_sidebar = False

pams_system/models/kpis.py
from django.db import models
from pams_system.models.maps import MapList, MapType
from pams_system.models.levels import InputData, MainLevel, Level, KPIWeightings
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext_lazy as _


class MainKpis(models.Model):
    maplist = models.ForeignKey(MapList, on_delete=models.SET_NULL, null=True)

    # kpi_id = models.AutoField(primary_key=True)

    class Meta:
        abstract = True


class KpiTypes(MainKpis):
    name = models.CharField(max_length=200, null=True)
    data_to_be_assigned_kpi = models.ForeignKey(MapType, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


# class KpiType(MainKpis, MPTTModel):
#     name = models.CharField(max_length=200, null=True)
#     data_to_be_assigned_kpi = models.ForeignKey(InputData, on_delete=models.SET_NULL, null=True)
#     parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
#                             related_name='children')
#
#     def __str__(self):
#         return self.name
#
#     class MPTTMeta:
#         level_attr = 'my_levels'
#         order_insertion_by = ['name'parent',']


class KpiIndividual(models.Model):
    YES = 'Y'
    NO = 'N'
    STATUS_CHOICES = (
        (YES, 'Yes'),
        (NO, 'No'),
    )
    status = models.CharField('Suspend Participant', max_length=255, choices=STATUS_CHOICES, default=NO)
    individual = models.CharField(max_length=200, null=True)
    is_suspended = models.BooleanField(_('Is Blocked'), help_text='button to toggle partcipant block and unblock',
                                       default=False)
    is_deleted = models.BooleanField(_('Is Deleted'), help_text='button to toggle participant deleted and undelete',
                                     default=False)

    def __str__(self):
        return self.individual

    class MPTTMeta:
        level_attr = 'kpi_levels'
        order_insertion_by = ['name', 'kpis']


class KpiParticipants(MainLevel, MPTTModel):
    YES = 'Y'
    NO = 'N'
    STATUS_CHOICES = (
        (YES, 'Yes'),
        (NO, 'No'),
    )
    status = models.CharField('Suspend Participant', max_length=255, choices=STATUS_CHOICES, default=NO)
    individual = models.CharField(max_length=200, null=True)
    is_suspended = models.BooleanField(_('Is Blocked'), help_text='button to toggle partcipant block and unblock',
                                       default=False)
    is_deleted = models.BooleanField(_('Is Deleted'), help_text='button to toggle participant deleted and undelete',
                                     default=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='children')
    levelset = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True)
    kpi_ind = TreeForeignKey(InputData, on_delete=models.CASCADE, null=True, blank=True,
                             related_name='kpi_individuals', verbose_name='Datastructure:')

    def __str__(self):
        return self.individual

    class MPTTMeta:
        level_attr = 'participant_levels'
        order_insertion_by = ['individual']




class KpiGroupset(MainLevel, MPTTModel):
    group = models.CharField(max_length=128, null=True, unique=True)
    # members = models.ManyToManyField(KpiParticipants, through='KpiMembership')
    is_deleted = models.BooleanField(_('Is Deleted'), help_text='button to toggle participant deleted and undelete',
                                     default=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='children')
    levelset = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True)
    kpi_group = TreeForeignKey(InputData, on_delete=models.CASCADE, null=True, blank=True,
                               related_name='kpi_groups', verbose_name='Datastructure:')

    # main_id = models.OneToOneField()

    def __str__(self):
        return self.group

    class MPTTMeta:
        level_attr = 'group_levels'
        order_insertion_by = ['group']

class KpiAssignee(MainLevel, MPTTModel):
    YES = 'Y'
    NO = 'N'
    STATUS_CHOICES = (
        (YES, 'Yes'),
        (NO, 'No'),
    )
    status = models.CharField('Suspend Participant', max_length=255, choices=STATUS_CHOICES, default=NO)
    individual = models.ForeignKey(KpiParticipants,on_delete=models.SET_NULL,null=True,blank=True)
    group = models.ForeignKey(KpiGroupset,on_delete=models.SET_NULL,null=True,blank=True)
    is_suspended = models.BooleanField(verbose_name='Mark Check Box below to suspend:', help_text='button to toggle partcipant block and unblock',
                                       default=False)
    is_deleted = models.BooleanField(_('Is Deleted'), help_text='button to toggle participant deleted and undelete',
                                     default=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='children')
    # levelset = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True)
    kpi_assign = TreeForeignKey(InputData, on_delete=models.CASCADE, null=True, blank=True,
                                related_name='kpi_assign', verbose_name='Datastructure:')

    def __str__(self):
        return self.individual

    class MPTTMeta:
        level_attr = 'participant_levels'
        order_insertion_by = ['individual']


class KpiAssignGroup(MainLevel, MPTTModel):
    group = models.CharField(max_length=128, null=True, unique=True)
    members = models.ManyToManyField(KpiAssignee, through='KpiMembership')
    is_deleted = models.BooleanField(_('Is Deleted'), help_text='button to toggle participant deleted and undelete',
                                     default=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='children')
    levelset = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True, related_name="group_level")
    kpi_assign_group = TreeForeignKey(InputData, on_delete=models.CASCADE, null=True, blank=True,
                                      related_name='kpi_group_assign', verbose_name='Datastructure:')

    # main_id = models.OneToOneField()

    def __str__(self):
        return self.group

    class MPTTMeta:
        level_attr = 'group_levels'
        order_insertion_by = ['group']


#
# class KpiGroups(models.Model):
#     group = models.CharField(max_length=128, null=True, unique=True)
#     members = models.ManyToManyField(KpiParticipants, through='KpiMembership')
#
#     def __str__(self):
#         return self.group


class KpiMembership(models.Model):  # intermediate model
    individual = models.ForeignKey(KpiAssignee, on_delete=models.CASCADE)  # source models
    group = models.ForeignKey(KpiAssignGroup, on_delete=models.CASCADE)  # source models
    # effective_date_joined = models.ForeignKey(InputData, on_delete=models.CASCADE, to_field="value_date",
    # blank=True, null=True)
    effective_date_joined = models.DateField(null=True)
    # main_id = models.OneToOneField(KpiGroupset, on_delete=models.CASCADE, parent_link=True, related_name='kpi_member_main')


class KpiMembers(MainLevel, models.Model):  # intermediate model
    individual = models.ForeignKey(KpiParticipants, on_delete=models.CASCADE)  # source models
    group = models.ForeignKey(KpiGroupset, on_delete=models.CASCADE)  # source models
    levelset = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True, blank=True)
    # effective_date_joined = models.ForeignKey(InputData, on_delete=models.CASCADE, to_field="value_date",
    # blank=True, null=True)
    effective_date_joined = models.DateField(null=True)
    # main_id = models.OneToOneField(KpiGroupset, on_delete=models.CASCADE, parent_link=True, related_name='kpi_member_main')


class KpiDates(models.Model):
    kpitype = models.ForeignKey(KpiTypes, on_delete=models.SET_NULL, related_name='kpi_date', null=True)
    period_date = models.DateField(null=True)

    def __str__(self):
        return self.period_date


class KpiWeights(models.Model):
    kpitype = models.ForeignKey(KpiTypes, on_delete=models.SET_NULL, related_name='kpi_weight', null=True)
    maplist = models.ForeignKey(MapList, on_delete=models.SET_NULL, related_name='kpi_maplist', null=True)
    data = models.ForeignKey(MapType, on_delete=models.SET_NULL, related_name='kpi_data', null=True, blank=True)
    weight = models.FloatField(null=True)

    def __float__(self):
        return self.weight


class KpiValue(models.Model):
    ind = models.ForeignKey(KpiIndividual, on_delete=models.SET_NULL, related_name='kpi_user', null=True, blank=True)
    group = models.ForeignKey(KpiGroupset, on_delete=models.SET_NULL, related_name='kpi_groups', null=True, blank=True)
    indicator = models.BooleanField(default=False)
    value = models.FloatField(null=True)
    period_date = models.DateField(auto_now_add=False, null=True, blank=True)


class KpiValueMain(models.Model):
    indicator = models.BooleanField(default=False)

    class Meta:
        abstract = True


class KpiValues(models.Model):
    individual = models.ForeignKey(KpiIndividual, on_delete=models.SET_NULL, related_name='kpi_individual',
                                   verbose_name='Participants', null=True, blank=True)
    group = models.ForeignKey(KpiGroupset, on_delete=models.SET_NULL, related_name='kpi_groupset', null=True,
                              blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='children', verbose_name='Categories')
    indicator = models.BooleanField(default=False)
    value = models.FloatField(null=True)

templates/kpis/create_kpi.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load l10n %}

<form method="post" id="sublevelform" data-specific-maplist-url="{% url 'ajax_specific_maplist_data'%}" novalidate>
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Create Kpi</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.label %}
            <div class="{% if field.errors %} invalid{% endif %}">
                {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <!--    <div class="controls {{ field_class }}"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>-->
        <!--        {% for choice_value, choice_instance in field.field.choices %}-->
        <!--        <label class="form-check checkbox{% if inline_class%}-{{ inline_class }}{% endif %}level-{{ choice_instance.level }}">-->
        <!--        <input type="checkbox" class="form-check-input"-->
        <!--            {% if choice_value in field.value or choice_value|stringformat:'s' in field.value or choice_value|stringformat:'s' == field.value|stringformat:'s' %}-->
        <!--            checked-->
        <!--            {% endif %}-->
        <!--            name="{{ field.html_name }}"-->
        <!--            id="id_{{field.html_name}}_{{forloop.counter}}"-->
        <!--            value="{{ choice_value|unlocalize }}"-->
        <!--            {{ field.field.widget.attrs|flatatt }}>-->
        <!--                <span>{{ choice_instance }}</span>-->
        <!--        </label>-->
        <!--        {% endfor %}-->
        <!--        </div>-->
    </div>

    <div class="modal-footer">
        <button type="button" class="submit-btn btn btn-success">Create</button>
    </div>

</form>
<script>
     $("#id_maptype").change(function(){
                 var url = $("#sublevelform").attr("data-specific-maplist-url"); // get the url of the specific maptype views
                 var maptypeId = $(this).val();  //get the selected maptype id from the html input

                 $.ajax({                          // initialize an ajax request
                   url:url,                        // set the url of the request
                   data:{
                     'maptype_data': maptypeId     // add the maptype id to the get parameters
                   },
                   success: function (data){       // data is the return of the specific maptype view
                     $("#id_maplist").html(data);  // replace contents of maptype with data that came from the server
                   }
                 });
          });


          $("#id_maptype").change(function () {
                var url = $("#sublevelform").attr("data-specific-maplist-url");  // post the url of the `load_maplist_data` view
                var maplistId = $(this).val();  // post the selected maplist ID from the HTML input

                $.ajax({                       // initialize an AJAX request
                  url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load/specific-maplist/)
                  data: {
                    'maplist_data': maplistId      // add the level id to the post parameters
                  },

                  success: function (data) {   // `data` is the return of the `load_sublevels` view function
                    $("#id_levelset").html(data);  // replace the contents of the sublevel input with the data that came from the server
                  }
                });
          });

<!--          $("#id_main").change(function () {-->
<!--                var url = $("#sublevelform").attr("data-specific-maplist-url");  // post the url of the `load_maplist_data` view-->
<!--                var levelId = $(this).val();  // post the selected maplist ID from the HTML input-->

<!--                $.ajax({                       // initialize an AJAX request-->
<!--                  url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load/specific-maplist/)-->
<!--                  data: {-->
<!--                    'level_data': levelId      // add the level id to the post parameters-->
<!--                  },-->

<!--                  success: function (data) {   // `data` is the return of the `load_sublevels` view function-->
<!--                    $("#id_name").html(data);  // replace the contents of the sublevel input with the data that came from the server-->
<!--                  }-->
<!--                });-->
<!--          });-->


    });


</script>

templates/kpis/create_kpi_group_value.html
{% load widget_tweaks %}

<form method="post" id="sublevelform" novalidate>
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Create Kpi Data</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.label %}
            <div class="{% if field.errors %} invalid{% endif %}">
                {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <label for="id_value_dates">Value Dates:</label>
        <select name="value_dates" id="id_value_dates" class="form-control" required>
            <option value="" selected>---------</option>
            {% for object in date_values %}
            <option value="{{object}}">{{object}}</option>
            {% endfor %}
        </select>
    </div>

    <div class="modal-footer">
        <button type="button" class="submit-btn btn btn-success">Create</button>
    </div>

</form>
<script>
      $("#id_level").change(function () {
      var url = $("#sublevelform").attr("data-sublevels-url");  // post the url of the `load_sublevels` view
      var levelId = $(this).val();  // post the selected level ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-sublevels/)
        data: {
          'level': levelId-1      // add the level id to the post parameters
        },

        success: function (data) {   // `data` is the return of the `load_sublevels` view function
          $("#id_previous_level_names").html(data);  // replace the contents of the sublevel input with the data that came from the server
          $("#id_previous_levels").html(data);
        }
      });


    });



</script>

templates/kpis/create_kpi_individual_value.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<form method="post" id="sublevelform" data-specific-kpi-url="{% url 'ajax_specific_kpi' %}" novalidate>
    <!--<form action="" method="POST">-->
    {% csrf_token %}
    <div class="modal-header">
        {% if group_checker %}
        <h3 class="modal-title">Input Group Data.</h3>
        {% elif individual_checker %}
        <h3 class="modal-title">Input Individual Data.</h3>
        {% else %}
        <h3 class="modal-title">None</h3>
        {% endif %}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <label for="id_content">Data:</label>
                <select name="content_set" id="id_content" class="form-control" required>
                    <option value="" selected>---------</option>
                    {% for object in data_values_filter %}
                    <option value="{{object.name}}" name="kpis">{{object.name}}</option>
                    {% endfor %}
                </select>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <label for="id_kpi">Kpis:</label>
                <!--                    {%if matching_string %}-->
                <select name="kpi" id="id_kpi" class="form-control" required>
                    <option value="56" selected>---------</option>
                    {% for object in weight_data.final_weight %}
                    <option value="{{object}}">{{object}}</option>
                    {% endfor %}
                </select>
                <!--                    {% endif %}-->
            </div>
        </div>
        <!--        {{ date_data }}-->
        <div class="row">
            <div class="col-lg-12">
                <label for="id_values">Value Dates:</label>

                <!--                    {%if matching_string %}-->
                <select name="values" id="id_values" class="form-control" required>
                    <option value="2019-05-02">---------</option>

                    <option value="{{object}}">{{object}}</option>

                </select>
                <!--                    {% endif %}-->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- <label for="id_weight">Weight Data:</label> -->
                <!--                    {%if matching_string %}-->
                <!-- <select name="weight" id="id_weight" class="form-control" required>
                    <option value="56" selected>---------</option>
                    {% for object in weight_data.final_weight %}
                    <option value="{{object}}">{{object}}</option>
                    {% endfor %}
                </select> -->
                <!--                    {% endif %}-->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                {%if individual_checker %}
                {{form.individual|as_crispy_field }}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                {%if group_checker %}
                <label for="id_grouping">Group_Sets:</label>
                <select name="grouping" id="id_grouping" class="form-control" required>
                    <option value="56" selected>---------</option>
                    {% for object in group_values_filter %}
                    <option value="{{object}}">{{object.group}}</option>
                    {% endfor %}
                </select>
                {% endif %}
            </div>
        </div>

        <label for="id_value_sets">ValueSet:</label>
        <input type="number" name="value_set" id="id_value_sets" class="form-control"/>
    </div>
    <div class="modal-footer">
        <button type="button" class="submit-btn btn btn-success">Submit to Database.</button>
    </div>
</form>
<script>

    $("#id_content").change(function () {
      var url = $("#sublevelform").attr("data-specific-kpi-url");;  // post the url of the `load_sublevels` view
      var levelId = $(this).val();  // post the selected level ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-sublevels/)
        data: {
          'kpi_val': levelId     // add the level id to the post parameters
        },


        success: function (data) {   // `data` is the return of the `load_sublevels` view function
          console.log(data);
          $("#id_kpi").html(data);  // replace the contents of the sublevel input with the data that came from the server
        }
      });
    });

    $("#id_kpi").change(function () {
      var url = $("#sublevelform").attr("data-specific-kpi-url");;  // post the url of the `load_sublevels` view
      var levelId = $(this).val();  // post the selected level ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-sublevels/)
        data: {
          'kpi_date': levelId     // add the level id to the post parameters
        },


        success: function (data) {   // `data` is the return of the `load_sublevels` view function
          console.log(data);
          $("#id_values").html(data);  // replace the contents of the sublevel input with the data that came from the server
        }
      });
    });


    $("#id_kpi").change(function () {
      var url = $("#sublevelform").attr("data-specific-kpi-url");;  // post the url of the `load_sublevels` view
      var levelId = $(this).val();  // post the selected level ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-sublevels/)
        data: {
          'weight': levelId     // add the level id to the post parameters
        },


        success: function (data) {   // `data` is the return of the `load_sublevels` view function
          console.log(data);
          $("#id_weight").html(data);  // replace the contents of the sublevel input with the data that came from the server
        }
      });
    });



</script>

templates/kpis/delete_kpi.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Kpi </h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete this data?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="delete-btn btn btn-danger">Delete</button>
  </div>

</form>

templates/kpis/kpi_membership.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Group Membership Management.</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-sm btn-success"><span class="fa fa-plus"></span>Add Member</button>
    <a href="#" class="btn btn-sm btn-success">
      <span class="pe-7s-back"></span>Remove Member</a>
  </div>

</form>

templates/kpis/stats_summary.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}
{% load crispy_forms_tags %}
{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}


{% block stylesheet %}



{% endblock %}
<!--CONTENTS-->
{% block content %}
<h3 class="modal-title">KPI Value Statistics</h3>
<h4><strong>Individual and Group Statistics</strong></h4>
<hr>
<a href="{% url 'kpiValueIndex' %}">Go back</a>
<form method="GET">
    <label>Participants/Users</label>
    <select name="kpi_set" id="id_kpi_set" class="form-control" required>
        <option value="" selected>---------</option>
        {% for object in kpi_users %}
        <option value="{{object.individual}}">{{object.individual}}</option>
        {% endfor %}
    </select>
    <label for="id_start_date">Start date:</label>
    <input type="date" id="id_start_date" name="start_date" class="form-control">
    <label for="id_end_date">End date:</label>
    <input type="date" id="id_end_date" name="end_date" class="form-control">
    <hr>
    <input class="btn btn-success" type="submit" value="Compute" name="Submit">
    <hr>
</form>
<ul>
  <table class="table table-hover" id="dev-table">
    <thead>
      <tr>
        <th>Value Date</th>
        <th>Summation</th>
      </tr>
    </thead>
    <tbody>
      {% for object in summation %}
      <tr>
          <td>{{object.vdate}}</td>
          <td>{{object.sum}}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
    {% for object in member_ranking %}
    {% if object.pk  == key %}
    <p>Ranking  -- > {{forloop.counter}} with a value of -->   {{object.value|floatformat:3}}  </p>
    {% endif %}
    {% endfor %}
</ul>
{% comment %} <a href="{% url 'print_documents' %}"><button type="button" class="btn btn-success">Print Results</button></a> {% endcomment %}
<script>
      $("#id_kpi_set").change(function () {
      var kpiUser = $(this).val();  // post the selected level ID from the HTML input

      $.ajax({
        url:"{% url 'stats_summary'  %}",                       // initialize an AJAX request
        data: {
          'kpi_users': kpiUser    // add the level id to the post parameters
        },
      });


    });


</script>
{% endblock %}

templates/kpis/update_kpi_group.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Kpis</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-success">Update</button>
  </div>

</form>