crm/urls.py
from django.urls import path
from . import views

app_name='crm'

urlpatterns=[
    path('client/create/', views.ClientCreate.as_view(), name='client_create'),
	path('client/list/',views.client_list,name='clients'),
	path('contact/list/',views.contact_list,name='contacts'),
    path('contact/create/', views.ContactCreate.as_view(), name='contact_create'),
	path('communications/index/',views.communications,name='communications'),
	path('communications/filters/',views.filter_parameter,name='filter_params'),
	path('communications/sms/',views.broadcast_sms,name='send_bulk_sms'),
	path('communications/sms/single/',views.broadcast_single_sms,name='send_single_sms'),
	path('communications/emails/',views.broadcast_emails,name='send_mass_email'),
	path('communications/emails/single/',views.broadcast_single_email,name='send_single_email'),
	path('communications/existing_filter/<int:search_id>/',views.use_existing_filter,name='use_existing_filter'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> performancesuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('select2/', include('django_select2.urls')),
    path('bs_index/',views.bootstrap_index),
    path('crm/',include('crm.urls',namespace='crm')),

    # path('accounts/', include('allauth.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'performance ADMINISTRATION'

admin.autodiscover()
admin.site.enable_nav_sidebar = False

crm/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class ClientManager(models.Model):
    STATUS_CHOICES=(
        ('E','Existing'),
        ('P','Potential'),
        ('F','Former'),
    )
    client_name=models.CharField(max_length=1028)
    country=models.CharField(max_length=1028)
    client_tel_no=models.CharField(max_length=60)
    client_email=models.EmailField()
    client_location=models.CharField(max_length=200)
    client_postal_address=models.CharField(max_length=350)
    client_status=models.CharField(max_length=10,choices=STATUS_CHOICES)
    facebook_account=models.URLField()
    twitter_account=models.URLField()
    instagram_account=models.URLField()
    linkedin_account=models.URLField()
    target=models.CharField(max_length=200,blank=True,null=True)
    nature_of_assignment=models.CharField(max_length=2000,blank=True,null=True)
    contract_period=models.CharField(max_length=2000,blank=True,null=True)
    final_proposal_amounts=models.CharField(max_length=2000,blank=True,null=True)
    

    def __str__(self):
        return self.client_name

class ContactManager(models.Model):
    STATUS_CHOICES=(
        ('A','Active'),
        ('E','Exited'),
    )
    #personal_details
    contact_name=models.CharField(max_length=250)
    position=models.CharField(max_length=255)
    personal_tel_no=models.CharField(max_length=255)
    personal_email=models.EmailField()
    personal_facebook_account=models.URLField()
    personal_twitter_account=models.URLField()
    personal_instagram_account=models.URLField()
    personal_linkedin_account=models.URLField()
    personal_status=models.CharField(max_length=10,choices=STATUS_CHOICES)
    #office_details
    client=models.ForeignKey(ClientManager,on_delete=models.CASCADE)
    service_line=models.CharField(max_length=250)
    target=models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.contact_name

    

class Message(models.Model):
    created_at=models.DateField(auto_now_add=True,blank=True,null=True)
    updated_at=models.DateField(auto_now_add=True,blank=True,null=True)
    sms=models.CharField(max_length=4096,blank=True,null=True)
    email_body=models.CharField(max_length=7168,blank=True,null=True)
    email_subject=models.CharField(max_length=1024,blank=True,null=True)
    contacts=models.ManyToManyField(ContactManager,blank=True,help_text="Press ctrl + click to add multiple users")
    clients=models.ManyToManyField(ClientManager,blank=True,help_text="Press ctrl + click to add multiple users")
    account_sid=models.CharField(max_length=1024,null=True,blank=True)
    api_version=models.CharField(max_length=200,null=True,blank=True)
    date_created=models.DateField(null=True,blank=True)
    date_sent=models.DateField(null=True,blank=True)
    date_updated=models.DateField(null=True,blank=True)
    delete=models.CharField(max_length=1200,null=True,blank=True)
    direction=models.CharField(max_length=1200,null=True,blank=True)
    error_code=models.CharField(max_length=1200,null=True,blank=True)
    error_message=models.CharField(max_length=1200,null=True,blank=True)
    feedback=models.CharField(max_length=1200,null=True,blank=True)
    fetch=models.CharField(max_length=1200,null=True,blank=True)
    from_who=models.CharField(max_length=1200,null=True,blank=True)
    media=models.CharField(max_length=1200,null=True,blank=True)
    messaging_service_sid=models.CharField(max_length=1200,null=True,blank=True)
    num_media=models.CharField(max_length=1200,null=True,blank=True)
    num_segments=models.CharField(max_length=1200,null=True,blank=True)
    price=models.CharField(max_length=1200,null=True,blank=True)
    price_unit=models.CharField(max_length=200,null=True,blank=True)
    sid=models.CharField(max_length=1200,null=True,blank=True)
    status=models.CharField(max_length=1200,null=True,blank=True)
    subresource_uris=models.CharField(max_length=1200,null=True,blank=True)
    to=models.CharField(max_length=1200,null=True,blank=True)
    update=models.CharField(max_length=1200,null=True,blank=True)
    uri=models.CharField(max_length=1200,null=True,blank=True)
    target_sms=models.CharField(max_length=200,null=True,blank=True)
    target_emails=models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.sms if self.sms else self.email_subject



class FilterSet(models.Model):
    search_parameter=models.CharField(max_length=2048,null=True,blank=True)
    filtered_list=models.CharField(max_length=2048,null=True,blank=True)
    user_filters=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return str(self.id)

crm/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from crm.forms.clientforms import (
    ClientForms,
    ContactForms,
)
from crm.forms.messageforms import (
    EmailForm,
    SmsForm,
    FilterForm
)
from .models import (
    ClientManager,
    ContactManager,
    Message,
    FilterSet
)
from .filters import (
    ClientFilter,
    ContactFilter
)
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.conf import settings
from twilio.rest import Client
from django.core.mail import send_mail, send_mass_mail

# Create your views here.


class ClientCreate(CreateView):
    '''
    this view creates clients.
    '''
    model = ClientManager
    template_name = 'taskmanager/task_create.html'
    form_class = ClientForms
    success_message = 'You have successfully created a project. Thank you'
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(ClientCreate, self).get_context_data(**kwargs)
        context['create_client'] = True
        return context

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            form.instance = self.object
            form.save()
        return super(ClientCreate, self).form_valid(form)


class ContactCreate(CreateView):
    '''
    this view creates contact persons
    '''
    model = ContactManager
    template_name = 'taskmanager/task_create.html'
    form_class = ContactForms
    success_message = 'You have successfully created a project. Thank you'
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(ContactCreate, self).get_context_data(**kwargs)
        context['create_contact'] = True
        return context

    def form_valid(self, form):
        self.object = form.save()
        if form.is_valid():
            form.instance = self.object
            form.save()
        return super(ContactCreate, self).form_valid(form)


def communications(request):
    context = {
        'communications': True
    }
    return render(request,'crm/communications.html',context)
    	


def filter_parameter(request):
    client_list = ClientManager.objects.all()
    client_filter = ClientFilter(request.GET, queryset=client_list)
    contact_list=ContactManager.objects.all()
    contact_filter=ContactFilter(request.GET,queryset=contact_list)
    client_name=request.GET.get('client_name')
    client_country=request.GET.get('country')
    client_tel_no=request.GET.get('client_tel_no')
    client_email=request.GET.get('client_email')
    client_location=request.GET.get('client_location')
    client_status=request.GET.get('client_status')
    nature_of_assignment=request.GET.get('nature_of_assignment')
    contract_period=request.GET.get('contract_period')
    client_query=[client_name,client_country,client_tel_no,client_email,
                client_location,client_status,nature_of_assignment,contract_period]
    # print(client_query)
    # print(res)
    client_results=ClientManager.objects.filter(
                            Q(country__in=client_query)|
                            Q(client_status__in=client_query)| 
                            Q(client_name__in=client_query)| 
                            Q(client_tel_no__in=client_query)|
                            Q(client_location__in=client_query)|
                            Q(client_email__in=client_query)
    )
    client_results=[client.client_name for client in client_results]

    contact_name=request.GET.get('contact_name')
    contact_position=request.GET.get('position')
    contact_tel_no=request.GET.get('personal_tel_no')
    contact_email=request.GET.get('personal_email')
    contact_status=request.GET.get('personal_status')
    contact_client=request.GET.get('client')
    contact_service_line=request.GET.get('service_line')
    contact_query=[contact_name,contact_position,contact_tel_no,contact_email,
                contact_status, contact_client,contact_service_line]
    contact_results=ContactManager.objects.filter(
                            Q(contact_name__in=contact_query)|
                            Q(position__in=contact_query)|
                            Q(personal_status__in=contact_query)| 
                            Q(personal_tel_no__in=contact_query)|
                            Q(personal_email__in=contact_query) |
                            Q(service_line__in=contact_query)
                )
    contact_results=[contact.contact_name for contact in contact_results]
    contact_query=list(filter(None,contact_query))
    client_query=list(filter(None,client_query))
    search_query=[contact_query,client_query]
    # import pdb;pdb.set_trace()
    # search_query=",".join(search_query)
    # print(contact_query)
    if contact_results or client_results:
        FilterSet.objects.create(search_parameter=search_query,
        filtered_list=[contact_results,client_results],user_filters=request.user)
    # print(contacts)            
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form=FilterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            if form.instance.search_parameter:
                q=form.instance.search_parameter
                clients=ClientManager.objects.filter(
                            Q(country__icontains=q)|
                            Q(client_location__icontains=q)|
                            Q(client_postal_address__icontains=q)| 
                            Q(client_status__icontains=q)| 
                            Q(client_name__icontains=q) | 
                            Q(client_tel_no__icontains=q)|
                            Q(client_email__icontains=q)
                )
                contacts=ContactManager.objects.filter(
                            Q(contact_name__icontains=q)|
                            Q(position__icontains=q)|
                            Q(personal_status__icontains=q)| 
                            Q(personal_tel_no__icontains=q)|
                            Q(personal_email__icontains=q) |
                            Q(service_line__icontains=q)
                )
                clients_data,contacts_data=[],[]
                
                for i in range(len(clients)):
                    clients_data.append(clients[i].client_name)
                for i in range(len(contacts)):
                    contacts_data.append(contacts[i].contact_name)
                form.instance.filtered_list=[clients_data,contacts_data]
            else:
                pass
                # clients=ClientManager.objects.all()
                # contacts=ContactManager.objects.all()
                # clients_data,contacts_data=[],[]
                # for i in range(len(clients)):
                #     clients_data.append(clients[i].client_name)
                # for i in range(len(contacts)):
                #     contacts_data.append(contacts[i].contact_name)
                # form.instance.filtered_list=[clients_data,contacts_data]
            
            form.save()
            return redirect('crm:communications')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = FilterForm()


  
    return render(request, 'crm/communications.html', {
                        'form': form,
                        'filters':True,
                        'contact_filter':contact_filter,
                        'client_filter':client_filter
                })

def use_existing_filter(request,search_id):
    get_data=FilterSet.objects.get(id=search_id)
    get_data.pk=None
    get_data.save()
    return redirect('crm:communications')

def broadcast_sms(request):
    # if this is a POST request we need to process the form data
    client=Client(settings.TWILIO_ACCOUNT_SID,settings.TWILIO_AUTH_TOKEN)
    get_data=FilterSet.objects.last()
    if get_data:
        get_data.user_filters=request.user
        get_data.save()
        client_data=eval(get_data.filtered_list[0])
        contact_data=eval(get_data.filtered_list[1])
        numbers_to_broadcast=[]
        get_contacts=ContactManager.objects.filter(Q(contact_name__in=contact_data))
        for contact in get_contacts:
            numbers_to_broadcast.append(contact.personal_tel_no)
        get_clients=ClientManager.objects.filter(Q(client_name__in=client_data))
        for client_ in get_clients:
            numbers_to_broadcast.append(client_.client_tel_no)
        if request.method == 'POST':
            # import pdb;pdb.set_trace()
            message_to_broadcast=request.POST.get('sms')
            # create a form instance and populate it with data from the request:
            form = SmsForm(request.POST)
            # import pdb;pdb.set_trace()
            # check whether it's valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required
                form.save()
                contact_set=form.instance.contacts
                client_set=form.instance.clients
                # ...
                contacts=contact_set.values('contact_name')
                clients=client_set.values('client_name')
                # import pdb;pdb.set_trace()
                contact_data,client_data=[],[]
                for contact_ in contacts:
                    if contact_:
                        contact_data.append(contact_['contact_name'])
                for clientel in clients:
                    if clientel:
                        client_data.append(clientel['client_name'])
                contacts_=ContactManager.objects.filter(contact_name__in=contact_data)

templates/crm/clients.html
{% extends '_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<div class="container">
    <table class="table table-responsive">
        <th>Client</th>  
        <th>Country</th>
        <th>client_tel_no</th>
        <th>client_email</th>
        <th>client_location</th>
        <th>client_postal_address</th>
        <th>client_status</th>
        <th>nature_of_assignment</th>
        <th>contract_period</th>
        <th>final_proposal_amounts</th>
        <th>contact_person</th>
        {% for client in clients %}
        <tr>
            <td>{{client.client_name}}</td>
            <td>{{client.country}}</td>
            <td>{{client.client_tel_no}}</td>
            <td>{{client.client_email}}</td>
            <td>{{client.client_location}}</td>
            <td>{{client.client_postal_address}}</td>
            <td>{{client.get_client_status_display}}</td>
            <td>{{client.nature_of_assignment}}</td>
            <td>{{client.contract_period}}</td>
            <td>{{client.final_proposal_amounts}}</td>
            <td>
                <ul>
                {% for contact in client.contactmanager_set.all %}
                 <li>{{contact.contact_name}}</li>
                {% endfor %}
                </ul>
            </td>
        </tr>
        {% endfor %}
    </table>

    
</div>


{% endblock content %}

templates/crm/communications.html
{% extends '_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<div class="row">
    <div class="col-1">
        <div class="container m-5">
            <a href="{% url 'crm:communications' %}"><i class="fa fa-home" aria-hidden="true"></i>CRM</a><hr>
            <b>Recent Searches</b>
            <ul>
                {% for filter in existing_filters %}
                <li><a href="{% url 'crm:use_existing_filter' filter.n %}">{{filter.search_parameter}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col-11">
        
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'crm:filter_params' %}">Filters <i class="fa fa-filter" aria-hidden="true"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="{% url 'crm:send_mass_email' %}" role="button" aria-expanded="false">Emails <i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'crm:send_mass_email' %}">Send Emails </a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Separated link</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="{% url 'crm:send_bulk_sms' %}" role="button" aria-expanded="false">Sms <i class="fa fa-comment" aria-hidden="true"></i></a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'crm:send_bulk_sms' %}">Send Sms</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Separated link</a></li>
                    </ul>
                </li>
              </ul>
            {% if communications %}
            <div class="card text-center">
                <div class="card-header">
                  Communications Module
                </div>
                <div class="card-body">
                    <h5 class="card-title">How to use the communications module:</h5>
                    <p class="card-text">Begin by clicking the <a href="{% url 'crm:filter_params' %}">filters</a>  tab in order to begin processing your <a href="{% url 'crm:filter_params' %}">filters</a> </p>
                    <p class="card-text">After processing filters you can choose to send an <a href="{% url 'crm:send_mass_email' %}">email</a>  or <a href="{% url 'crm:send_bulk_sms' %}">sms</a></p>
                    <p class="card-text">Recent Searches show up alongside in order to simplify your filter process</p>
                </div>
              </div>
            {% elif filters %}
            <form action="{% url 'crm:filter_params' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="badge-sm badge-success"><i class="fa fa-search"></i></button>
            </form>
            <hr>
            <div class="row">
              <div class="col-6">
                <h5>Client filters</h5>
                <form method="get">
                  {{ client_filter.form|crispy}}
                  <button type="submit" class="btn-sm btn-success">Search</button>
                </form>
              </div>
              <div class="col-6">
                <h5>Contact Persons Filters</h5>
                <form method="get">
                  {{ contact_filter.form|crispy }}
                  <button type="submit" class="btn-sm btn-success">Search</button>
                </form>
              </div>
            </div>
            
            
            {% elif emails %}
            <form action="{% url 'crm:send_mass_email' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="send emails" class="btn-sm btn-success">
            </form>    
            {% elif sms %}
            <form action="{% url 'crm:send_bulk_sms' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="send sms" class="btn-sm btn-success">
            </form>
            {% endif %}
               
           
       </div>
    </div>
</div>


{% endblock %}

templates/crm/contacts.html
{% extends '_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<div class="container">
    <table class="table table-responsive">
        <th>contact_person</th>
        <th>position</th>
        <th>personal_tel_no</th>
        <th>personal_email</th>
        <th>client</th>
        <th>service_line</th>
        {% for contact in contacts %}
        <tr>
            <td>{{contact.contact_name}}</td>
            <td>{{contact.position}}</td>
            <td>{{contact.personal_tel_no}}</td>
            <td>{{contact.personal_email}}</td>
            <td>{{contact.client}}</td>
            <td>{{contact.service_line}}</td>
        </tr>
        {% endfor %}
    </table>

    
</div>


{% endblock content %}